pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'java'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        
        stage ('Compile') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true -f OrganoCart/pom.xml clean compile' 
            }
        }
        
        stage ('Test') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true  -f OrganoCart/pom.xml clean test' 
            }
        }
        
        stage ('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true  -f OrganoCart/pom.xml install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
    }
}
