pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'java'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        
        stage ('Compile') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true -f OrganoCart/pom.xml clean compile' 
            }
        }
        
        stage ('Test') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true  -f OrganoCart/pom.xml clean test' 
            }
        }
        
        stage ('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true  -f OrganoCart/pom.xml install' 
            }
        }
        stage ('Build Docker Image') {
            steps {
                sh 'docker -H :1234 rmi -f organocart-green || true'
                sh 'docker -H :1234 build -f OrganoCart/dockerfile -t organocart-green .' 
                
            }
        }
        
        stage ('Push Image to Artifactory') {
            steps {
                sh 'docker -H :1234 login -u santoshpkatageri -p Qwerty@12345 organocart-docker.jfrog.io' 
                sh 'docker -H :1234 tag organocart-green organocart-docker.jfrog.io/organocart-green:latest'
                sh 'docker -H :1234 push organocart-docker.jfrog.io/organocart-green:latest'
            }
        }
        
        stage ('Deploy to Green ENV') {
            steps {
                sh 'docker -H :1234 stop organocart-green || true'
                sh 'docker -H :1234 rm organocart-green || true'
                sh 'docker -H :1234 pull organocart-docker.jfrog.io/organocart-green:latest'
                sh 'docker -H :1234 run -d --name organocart-green -p 8086:8080 organocart-docker.jfrog.io/organocart-green:latest'

            }
        }
    }
}
